
name: RDP NGROK

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup RDP & Ngrok
      run: |
        choco install ngrok -y
        ngrok config add-authtoken 2z0CIIa2wlP8MNjX9CnJWB6JR6a_2fCCtNLVbbhgcaYtoMcc2
        net user RDPuser RdpPass123! /add
        net localgroup administrators RDPuser /add
        powershell -Command "Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0"
        powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
        start /b ngrok tcp 3389
        echo USER: RDPuser
        echo PASS: RdpPass123!
        timeout /t 300
